export const GET_CART = "GET_CART";
export const UPDATE_CART = "UPDATE_CART";
export const ADD_TO_CART = "ADD_TO_CARD";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const INCERATE_QUANTITY = "INCERATE_QUANTITY";
export const DECORATE_QUANTITY = "DECORATE_QUANTITY";